version: '3.4'

services:
  NodeA:  
    image: akigi/vsomeip-node:latest
    restart: always
    container_name: node_a
    privileged: true
    volumes:
      - ./code:/code
    networks:
      node_AB_net:
        ipv4_address: 192.168.100.2
    ports:
      - '10001:22'

  NodeB:
    image: akigi/vsomeip-node:latest
    restart: always
    container_name: node_b
    volumes:
      - ./code:/code
    networks:
      node_AB_net:
        ipv4_address: 192.168.100.3
      node_BC_net:
        ipv4_address: 192.168.200.3
    ports:
      - '10002:22'

  NodeC:
    image: akigi/vsomeip-node:latest
    restart: always
    container_name: node_c
    volumes:
      - ./code:/code
    networks:
      node_BC_net:
        ipv4_address: 192.168.200.2
    ports:
      - '10003:22'

networks:
  node_AB_net:
    name: node_AB_net
    ipam:
      config:
        - subnet: 192.168.100.0/24
  node_BC_net:
    name: node_BC_net
    ipam:
      config:
        - subnet: 192.168.200.0/24